// <auto-generated />
using System;
using Intelektual_Tizimlar_Amaliyot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intelektual_Tizimlar_Amaliyot.Migrations
{
    [DbContext(typeof(IntelektDB))]
    [Migration("20211224174554_Initial_Create")]
    partial class Initial_Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("intelekt")
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intelektual_Tizimlar_Amaliyot.Models.Agreement", b =>
                {
                    b.Property<Guid>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("Intelektual_Tizimlar_Amaliyot.Models.Atribute", b =>
                {
                    b.Property<Guid>("AtributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("AtributeId");

                    b.ToTable("Atributes");
                });

            modelBuilder.Entity("Intelektual_Tizimlar_Amaliyot.Models.Condition", b =>
                {
                    b.Property<Guid>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ConditionId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Intelektual_Tizimlar_Amaliyot.Models.Situation", b =>
                {
                    b.Property<Guid>("SituationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("SituationId");

                    b.HasIndex("AgreementId");

                    b.HasIndex("AtributeId");

                    b.HasIndex("ConditionId");

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("Intelektual_Tizimlar_Amaliyot.Models.Situation", b =>
                {
                    b.HasOne("Intelektual_Tizimlar_Amaliyot.Models.Atribute", "Atribute")
                        .WithMany("Situations")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intelektual_Tizimlar_Amaliyot.Models.Agreement", "Agreement")
                        .WithMany("Situations")
                        .HasForeignKey("AtributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intelektual_Tizimlar_Amaliyot.Models.Condition", "Condition")
                        .WithMany("Situations")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
